### ISSUE TITLE
Background "images/backgrounds/bg-1.jpg" isn't showing in cta.yml (english only)

### ISSUE THREAD

**Issue by ydarchi** [ydarchi/www.yd.archi#3]
Hi bro, 

Can you please help me fixing the "images/backgrounds/bg-1.jpg" missing image when site is deployed. It appears only when on the **english** version. I checked the rep. and the file is there, same name as mentioned in textmate.

**Comment by drupol** [comment]
Taking care of this now.

**Comment by drupol** [comment]
The syntax of the file `cta.yml` was changed due to the theme upgrade. I synced it and it should be fine, could you verify ?

**Comment by ydarchi** [comment]
Thx all good !
